#!/bin/sh
set -eu

rootfs_input=${1:?missing target rootfs}
rootfs=$(realpath -e -- "$rootfs_input")
test -n "$rootfs"
test "$rootfs" != "/"
test -d "$rootfs/etc"

source_root=${SRCROOT:?missing rpi-image-gen source root}
repository_root=$(realpath -e -- "$source_root/..")
profile="$repository_root/image/overlays/etc/NetworkManager/system-connections/rave-setup.nmconnection"
dnsmasq="$repository_root/image/overlays/etc/rave/network/dnsmasq.conf"
sysctl="$repository_root/image/overlays/etc/sysctl.d/90-rave-network-isolation.conf"
runtime_network="$repository_root/image/overlays/etc/systemd/network/10-rave-ethernet.network"
nm_unmanaged="$repository_root/image/overlays/etc/NetworkManager/conf.d/10-rave-unmanaged-runtime.conf"
nm_wifi_backend="$repository_root/image/overlays/etc/NetworkManager/conf.d/20-rave-wifi-backend.conf"
network_ipc="$repository_root/setup-ui/rave_network_ipc"
network_daemon="$repository_root/setup-ui/rave_networkd"
networkd_unit="$repository_root/systemd/rave-networkd.service"
dhcp_unit="$repository_root/systemd/rave-management-dhcp.service"
test -f "$profile"
test -f "$dnsmasq"
test -f "$sysctl"
test -f "$runtime_network"
test -f "$nm_unmanaged"
test -f "$nm_wifi_backend"
test -d "$network_ipc"
test -d "$network_daemon"
test -f "$networkd_unit"
test -f "$dhcp_unit"
rm -f -- "$rootfs/etc/systemd/network/01-eth0.network"
rm -f -- "$rootfs/etc/systemd/network/02-wlan0.network"
rm -f -- "$rootfs/etc/systemd/system/multi-user.target.wants/iwd.service"
ln -sf /dev/null "$rootfs/etc/systemd/system/iwd.service"
install -d -m 0700 "$rootfs/etc/NetworkManager/system-connections"
install -d -m 0755 "$rootfs/etc/NetworkManager/conf.d" "$rootfs/etc/systemd/network"
install -d -m 0755 "$rootfs/etc/rave/network" "$rootfs/etc/sysctl.d"
install -d -m 0755 "$rootfs/var/lib/misc"
install -m 0600 "$profile" "$rootfs/etc/NetworkManager/system-connections/rave-setup.nmconnection"
install -m 0644 "$dnsmasq" "$rootfs/etc/rave/network/dnsmasq.conf"
install -m 0644 "$sysctl" "$rootfs/etc/sysctl.d/90-rave-network-isolation.conf"
install -m 0644 "$runtime_network" "$rootfs/etc/systemd/network/10-rave-ethernet.network"
install -m 0644 "$nm_unmanaged" "$rootfs/etc/NetworkManager/conf.d/10-rave-unmanaged-runtime.conf"
install -m 0644 "$nm_wifi_backend" "$rootfs/etc/NetworkManager/conf.d/20-rave-wifi-backend.conf"
install -d -m 0755 \
  "$rootfs/opt/rave/management/rave_network_ipc" \
  "$rootfs/opt/rave/management/rave_networkd" \
  "$rootfs/usr/lib/systemd/system" \
  "$rootfs/etc/systemd/system/multi-user.target.wants"
rsync -a --delete --exclude='__pycache__' --exclude='*.pyc' \
  "$network_ipc/" "$rootfs/opt/rave/management/rave_network_ipc/"
rsync -a --delete --exclude='__pycache__' --exclude='*.pyc' \
  "$network_daemon/" "$rootfs/opt/rave/management/rave_networkd/"
find "$rootfs/opt/rave/management" -type d -exec chmod 0755 {} +
find "$rootfs/opt/rave/management" -type f -exec chmod 0644 {} +
chroot "$rootfs" /bin/chown -R root:root /opt/rave/management
install -m 0644 "$networkd_unit" "$rootfs/usr/lib/systemd/system/rave-networkd.service"
install -m 0644 "$dhcp_unit" "$rootfs/usr/lib/systemd/system/rave-management-dhcp.service"
ln -sf /usr/lib/systemd/system/NetworkManager.service "$rootfs/etc/systemd/system/multi-user.target.wants/NetworkManager.service"
ln -sf /usr/lib/systemd/system/systemd-networkd.service "$rootfs/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
ln -sf /usr/lib/systemd/system/rave-networkd.service "$rootfs/etc/systemd/system/multi-user.target.wants/rave-networkd.service"
rm -f -- "$rootfs/etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service"

chroot "$rootfs" /usr/sbin/dnsmasq --test \
  --conf-file=/etc/rave/network/dnsmasq.conf --no-hosts --no-resolv
